# Deploy ClusterIP Services
apiVersion: v1
kind: Service
metadata:
  name: eos-catalog-api-service
  labels:
    app: eos-catalog-api

spec:
  selector:
    app: eos-catalog-api

  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081

