# Deploy ClusterIP Services
apiVersion: v1
kind: Service
metadata:
  name: eos-payment-api-service
  labels:
    app: eos-payment-api

spec:
  selector:
    app: eos-payment-api

  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083

