# Deploy ClusterIP Services
apiVersion: v1
kind: Service
metadata:
  name: eos-kart-api-service
  labels:
    app: eos-kart-api

spec:
  selector:
    app: eos-kart-api

  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082

