apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos-kart-api
  labels:
    app: eos-kart-api
spec:
  replicas:  {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: eos-kart-api
  template:
    metadata:
      labels:
        app: eos-kart-api
    spec:
      containers:
      - name: eos-kart-api
        image: docker.io/dpthub/eos-kart-api:latest
        ports:
        - containerPort: 8082
