# Deploy ClusterIP Services
apiVersion: v1
kind: Service
metadata:
  name: eos-registry-api-service
  labels:
    app: eos-registry-api

spec:
  selector:
    app: eos-registry-api

  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761

