# Deploy ClusterIP Services
apiVersion: v1
kind: Service
metadata:
  name: eos-user-api-service
  labels:
    app: eos-user-api

spec:
  selector:
    app: eos-user-api

  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085

