apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eos-react-webapp
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eos-react-webapp-service
            port:
              number: 3000
  ingressClassName: nginx
